import { supabase, isSupabaseConfigured } from './supabase.js';
const $=id=>document.getElementById(id);let registry=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const formatDate=v=>v?new Intl.DateTimeFormat('ar-LY',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
const toast=msg=>{const t=$('adminToast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)};
const makeCode=()=>{const part=()=>crypto.getRandomValues(new Uint32Array(1))[0].toString(36).toUpperCase().padStart(4,'0').slice(0,4);return `VILLA-${part()}-${part()}`};
async function sha256(value){const bytes=new TextEncoder().encode(value);const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function state(x){if(x.status==='revoked')return['revoked','ملغى'];if(x.status==='redeemed')return['active','مفعّل'];return['unused','غير مفعّل']}
function render(){const q=($('searchCodes').value||'').toLowerCase(),rows=registry.filter(x=>`${x.customer_name} ${x.property_name} ${x.code_hint} ${x.assigned_email||''}`.toLowerCase().includes(q));$('totalCodes').textContent=registry.length;$('activeCodes').textContent=registry.filter(x=>x.status==='redeemed').length;$('unusedCodes').textContent=registry.filter(x=>x.status==='issued'||x.status==='reserved').length;$('revokedCodes').textContent=registry.filter(x=>x.status==='revoked').length;$('emptyState').style.display=rows.length?'none':'block';$('codesBody').innerHTML=rows.map(x=>{const [cls,label]=state(x);return `<tr><td><b>${esc(x.customer_name||'—')}</b><small>${esc(x.device_limit||1)} جهاز</small></td><td>${esc(x.property_name||'—')}<small>${x.expires_at?'ينتهي '+formatDate(x.expires_at):'بدون انتهاء'}</small></td><td><span class="code">${esc(x.code_hint||'VILLA-••••-••••')}</span></td><td><span class="badge ${cls}">${label}</span></td><td>${formatDate(x.last_seen_at||x.activated_at)}</td><td><div class="row-actions">${x.status==='revoked'?'':'<button class="revoke" data-revoke="'+esc(x.code_hash)+'">إلغاء</button>'}</div></td></tr>`}).join('')}
async function loadCodes(){const {data,error}=await supabase.rpc('vt_admin_list_activation_codes');if(error){toast('تعذر قراءة سجل الأكواد: '+error.message);return}registry=data||[];render()}
async function login(e){e.preventDefault();if(!isSupabaseConfigured){$('adminLoginMessage').textContent='إعدادات Supabase غير موجودة';return}const {error}=await supabase.auth.signInWithPassword({email:$('adminEmail').value.trim(),password:$('adminPassword').value});if(error){$('adminLoginMessage').textContent='بيانات الدخول غير صحيحة أو الحساب غير مفعل';return}$('adminGate').classList.add('hidden');toast('تم تسجيل الدخول عبر Supabase');await loadCodes()}
async function boot(){if(!isSupabaseConfigured){$('adminLoginMessage').textContent='لم يتم إعداد Supabase';return}const {data}=await supabase.auth.getSession();if(data.session){$('adminGate').classList.add('hidden');await loadCodes()}}
$('adminLogin').onsubmit=login;
$('codeForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),raw=makeCode(),days=Number(d.duration),expires=days?new Date(Date.now()+days*86400000).toISOString():null;const {error}=await supabase.rpc('vt_admin_create_activation_code',{p_code_hash:await sha256(raw),p_code_hint:`VILLA-••••-${raw.slice(-4)}`,p_customer_name:d.customer,p_property_name:d.property||'',p_assigned_email:d.email||'',p_expires_at:expires,p_device_limit:Number(d.devices||1)});if(error){toast('تعذر حفظ الكود: '+error.message);return}$('generatedCode').textContent=raw;$('generatedBox').hidden=false;e.target.reset();$('codeForm').querySelector('[name="devices"]').value='1';await loadCodes();toast('تم حفظ الكود في Supabase — انسخه الآن')};
$('copyGenerated').onclick=()=>navigator.clipboard?.writeText($('generatedCode').textContent).then(()=>toast('تم نسخ الكود'));
$('searchCodes').oninput=render;
$('logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};
document.body.addEventListener('click',async e=>{const hash=e.target.dataset.revoke;if(!hash)return;if(!confirm('هل تريد إلغاء هذا الكود؟'))return;const {error}=await supabase.rpc('vt_admin_revoke_activation_code',{p_code_hash:hash});if(error)toast('تعذر إلغاء الكود');else{await loadCodes();toast('تم إلغاء الكود سحابياً')}});
boot();
