import { isSupabaseConfigured, listVillas, saveVilla, removeVilla, listBookings, findOverlap, saveBooking, removeBooking } from './supabase.js';

const demoVillas = [
  { id:'v1', name:'فيلا أوريانا', location:'ساحل البحر — الصف الأول', bedrooms:4, price:850, status:'available', accent:'image-1' },
  { id:'v2', name:'فيلا لازورد', location:'الحدائق الملكية', bedrooms:3, price:720, status:'booked', accent:'image-2' },
  { id:'v3', name:'فيلا ميراج', location:'تلال المدينة', bedrooms:5, price:1100, status:'available', accent:'image-3' },
  { id:'v4', name:'فيلا سيلين', location:'الخليج الغربي', bedrooms:3, price:680, status:'maintenance', accent:'image-4' },
  { id:'v5', name:'فيلا نوفا', location:'المرسى — إطلالة بانورامية', bedrooms:4, price:930, status:'available', accent:'image-5' },
  { id:'v6', name:'فيلا إلورا', location:'الواحة الخضراء', bedrooms:6, price:1450, status:'available', accent:'image-6' }
];
const demoBookings = [
  { id:'b1', villa_id:'v2', guest_name:'سارة المنصوري', guest_phone:'091 222 8417', check_in:'2026-09-28', check_out:'2026-10-02', nights:4, total:2880, payment_status:'paid', status:'confirmed' },
  { id:'b2', villa_id:'v1', guest_name:'عمر الشريف', guest_phone:'092 671 2039', check_in:'2026-10-03', check_out:'2026-10-05', nights:2, total:1700, payment_status:'deposit', status:'confirmed' },
  { id:'b3', villa_id:'v3', guest_name:'ليان الترهوني', guest_phone:'091 498 1102', check_in:'2026-10-05', check_out:'2026-10-09', nights:4, total:4400, payment_status:'pending', status:'pending' },
  { id:'b4', villa_id:'v5', guest_name:'خالد أبوسيف', guest_phone:'092 148 7743', check_in:'2026-10-11', check_out:'2026-10-14', nights:3, total:2790, payment_status:'paid', status:'confirmed' },
  { id:'b5', villa_id:'v1', guest_name:'نور الحداد', guest_phone:'091 817 5520', check_in:'2026-09-20', check_out:'2026-09-22', nights:2, total:1700, payment_status:'paid', status:'confirmed' }
];
let villas = [...demoVillas], bookings = [...demoBookings], villaFilter = 'all';
const money = n => `${Number(n || 0).toLocaleString('ar-LY')} د.ل`;
const villaName = id => villas.find(v => v.id === id)?.name || 'فيلا غير معروفة';
const statusText = { available:'متاحة', booked:'محجوزة', maintenance:'صيانة', confirmed:'مؤكد', pending:'معلق', cancelled:'ملغي', paid:'مدفوع بالكامل', deposit:'عربون', pendingPay:'معلق' };
const $ = id => document.getElementById(id);
function toast(message, good = true){ const t=$('toast'); t.querySelector('p').textContent=message; t.querySelector('span').textContent=good?'✓':'!'; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),3000); }
function openModal(html){ $('modalContent').innerHTML=html; $('modalBackdrop').classList.add('open'); }
function closeModal(){ $('modalBackdrop').classList.remove('open'); }
function switchView(view){ document.querySelectorAll('.view').forEach(v=>v.classList.remove('active')); $(`${view}View`).classList.add('active'); document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); if(view==='villas') renderVillas(); if(view==='bookings') renderBookings(); $('sidebar').classList.remove('open'); }
function normalizeVilla(v){ return {...v, accent:v.accent || 'image-1', bedrooms:v.bedrooms || 3, price:v.price || 0}; }
async function loadData(){
  if(!isSupabaseConfigured){ $('connectionLabel').textContent='وضع تجريبي — بيانات محلية'; return; }
  const [vr,br]=await Promise.all([listVillas(),listBookings()]);
  if(!vr.error && vr.data?.length) villas=vr.data.map(normalizeVilla);
  if(!br.error && br.data?.length) bookings=br.data.map(b=>({...b, villa_id:b.villa_id, villa_name:b.villas?.name}));
  $('connectionLabel').textContent='متصل بـ Supabase';
}
async function persistVilla(v,id){ if(isSupabaseConfigured){const r=await saveVilla(v,id);if(r.error) throw r.error;} }
async function persistBooking(b,id){ if(isSupabaseConfigured){const r=await saveBooking(b,id);if(r.error) throw r.error;} }
function calculateStats(){ const revenue=bookings.filter(b=>b.status!=='cancelled').reduce((s,b)=>s+Number(b.total||0),0); const active=bookings.filter(b=>b.status==='confirmed').length; const occupancy=Math.min(100,Math.round((active/Math.max(villas.length*2,1))*100)); $('totalRevenue').textContent=money(revenue); $('occupancyRate').textContent=`${occupancy}%`; $('activeBookings').textContent=active; $('totalVillas').textContent=villas.length; $('availableVillas').textContent=villas.filter(v=>v.status==='available').length; $('allBookingsCount').textContent=bookings.length; $('paidBookingsCount').textContent=bookings.filter(b=>b.payment_status==='paid').length; $('pendingBookingsCount').textContent=bookings.filter(b=>b.payment_status!=='paid').length; $('confirmedRevenue').textContent=money(bookings.filter(b=>b.status==='confirmed').reduce((s,b)=>s+Number(b.total||0),0)); $('bookingTotal').textContent=bookings.length; }
function renderRecent(){ $('recentBookingsBody').innerHTML=bookings.slice(0,5).map(b=>`<tr><td><span class="guest-name">${b.guest_name}</span><span class="guest-phone">${b.guest_phone||''}</span></td><td>${villaName(b.villa_id)}</td><td>${b.check_in}</td><td>${b.check_out}</td><td><span class="badge ${b.status}">${statusText[b.status]}</span></td><td>${money(b.total)}</td><td><button class="kebab">•••</button></td></tr>`).join('') || '<tr><td colspan="7" class="empty">لا توجد حجوزات بعد</td></tr>'; }
function renderVillas(){ const q=($('villaSearch')?.value||'').toLowerCase(); const list=villas.filter(v=>(villaFilter==='all'||v.status===villaFilter)&&v.name.toLowerCase().includes(q)); $('villaGrid').innerHTML=list.map(v=>`<article class="villa-card"><div class="villa-image ${v.accent}"><span>⌂</span><span class="villa-status badge ${v.status}">${statusText[v.status]}</span></div><div class="villa-info"><h3>${v.name}</h3><p>${v.location||'موقع مميز'} </p><div class="villa-meta"><span>♧ ${v.bedrooms} غرف</span><span>${money(v.price)} / ليلة</span></div><div class="villa-actions"><button data-edit-villa="${v.id}">تعديل</button><button data-delete-villa="${v.id}">حذف</button></div></div></article>`).join('') || '<div class="empty">لا توجد فيلات مطابقة.</div>'; }
function renderBookings(){ const q=($('bookingSearch')?.value||'').toLowerCase(), sf=$('bookingStatusFilter')?.value||'all'; const list=bookings.filter(b=>(sf==='all'||b.status===sf)&&(`${b.guest_name} ${villaName(b.villa_id)}`).toLowerCase().includes(q)); $('bookingsBody').innerHTML=list.map(b=>`<tr><td><span class="guest-name">${b.guest_name}</span><span class="guest-phone">${b.guest_phone||''}</span></td><td>${villaName(b.villa_id)}</td><td>${b.check_in}<br><span class="guest-phone">إلى ${b.check_out}</span></td><td>${b.nights}</td><td><span class="pay-badge ${b.payment_status==='paid'?'paid':''}">${statusText[b.payment_status]||'معلق'}</span></td><td><span class="badge ${b.status}">${statusText[b.status]}</span></td><td>${money(b.total)}</td><td><button class="text-btn" data-invoice="${b.id}">فاتورة</button></td></tr>`).join('') || '<tr><td colspan="8" class="empty">لا توجد حجوزات مطابقة.</td></tr>'; calculateStats(); }
function drawCharts(){ if(!window.Chart)return; const base={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:'#71819a',font:{family:'Cairo',size:9}}},y:{grid:{color:'rgba(255,255,255,.06)'},ticks:{color:'#71819a',font:{family:'Cairo',size:9}}}}}; new Chart($('revenueChart'),{type:'line',data:{labels:['أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر'],datasets:[{data:[9200,11800,10400,15100,13700,bookings.reduce((s,b)=>s+b.total,0)],borderColor:'#d4af37',backgroundColor:'rgba(212,175,55,.13)',fill:true,tension:.42,pointRadius:3,pointBackgroundColor:'#d4af37'}]},options:base}); const counts=['paid','deposit','pending'].map(s=>bookings.filter(b=>b.payment_status===s).length); new Chart($('bookingChart'),{type:'doughnut',data:{labels:['مدفوع','عربون','معلق'],datasets:[{data:counts,backgroundColor:['#33c184','#d4af37','#64748b'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'76%',plugins:{legend:{display:false}}}}); $('bookingLegend').innerHTML=['مدفوع','عربون','معلق'].map((x,i)=>`<span><i style="background:${['#33c184','#d4af37','#64748b'][i]}"></i>${x} ${counts[i]}</span>`).join(''); }
function villaForm(v=null){ openModal(`<div><p class="eyebrow">المحفظة العقارية</p><h2>${v?'تعديل بيانات الفيلا':'إضافة فيلا جديدة'}</h2><p>أدخل تفاصيل الوحدة لتظهر في محفظتك.</p><form id="villaForm"><div class="form-grid"><div class="form-field"><label>اسم الفيلا</label><input name="name" required value="${v?.name||''}" placeholder="مثال: فيلا أوريانا"></div><div class="form-field"><label>السعر لليلة (د.ل)</label><input name="price" type="number" required value="${v?.price||''}"></div><div class="form-field full"><label>الموقع والوصف المختصر</label><input name="location" value="${v?.location||''}" placeholder="ساحل البحر — الصف الأول"></div><div class="form-field"><label>عدد الغرف</label><input name="bedrooms" type="number" min="1" value="${v?.bedrooms||3}"></div><div class="form-field"><label>الحالة</label><select name="status"><option value="available" ${v?.status==='available'?'selected':''}>متاحة</option><option value="booked" ${v?.status==='booked'?'selected':''}>محجوزة</option><option value="maintenance" ${v?.status==='maintenance'?'selected':''}>صيانة</option></select></div></div><button class="primary-btn">حفظ بيانات الفيلا</button></form></div>`); $('villaForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const item=normalizeVilla({...v,...d,id:v?.id||`v${Date.now()}`,price:Number(d.price),bedrooms:Number(d.bedrooms)});try{await persistVilla({name:item.name,location:item.location,price:item.price,bedrooms:item.bedrooms,status:item.status},v?.id);if(v)villas=villas.map(x=>x.id===v.id?item:x);else villas.unshift(item);closeModal();renderVillas();calculateStats();toast('تم حفظ بيانات الفيلا بنجاح');}catch(err){toast('تعذر الحفظ في Supabase',false);}}; }
function bookingForm(){ const villaOptions=villas.filter(v=>v.status!=='maintenance').map(v=>`<option value="${v.id}">${v.name} — ${money(v.price)}</option>`).join(''); openModal(`<div><p class="eyebrow">محرك الحجوزات</p><h2>إنشاء حجز جديد</h2><p>يتم منع تضارب المواعيد تلقائياً قبل الحفظ.</p><form id="bookingForm"><div class="form-grid"><div class="form-field full"><label>اسم الضيف</label><input name="guest_name" required placeholder="الاسم الكامل"></div><div class="form-field"><label>رقم الهاتف</label><input name="guest_phone" placeholder="091 ..."></div><div class="form-field"><label>الفيلا</label><select name="villa_id" id="bookingVilla">${villaOptions}</select></div><div class="form-field"><label>تاريخ الوصول</label><input name="check_in" id="checkIn" type="date" required></div><div class="form-field"><label>تاريخ المغادرة</label><input name="check_out" id="checkOut" type="date" required></div><div class="form-field"><label>حالة الدفع</label><select name="payment_status"><option value="paid">مدفوع بالكامل</option><option value="deposit">عربون</option><option value="pending">معلق</option></select></div><div class="form-field"><label>حالة الحجز</label><select name="status"><option value="confirmed">مؤكد</option><option value="pending">معلق</option></select></div></div><div class="form-total"><span>الإجمالي التقديري <small id="nightCount">(0 ليلة)</small></span><strong id="bookingTotalPreview">0 د.ل</strong></div><button class="primary-btn">تأكيد الحجز</button></form></div>`); const update=()=>{const v=villas.find(x=>x.id===$('bookingVilla').value),a=new Date($('checkIn').value),b=new Date($('checkOut').value),n=Math.max(0,Math.ceil((b-a)/86400000));$('nightCount').textContent=`(${n} ليلة)`;$('bookingTotalPreview').textContent=money(n*(v?.price||0));}; ['bookingVilla','checkIn','checkOut'].forEach(id=>$(id).addEventListener('change',update)); $('bookingForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const a=new Date(d.check_in),b=new Date(d.check_out),n=Math.ceil((b-a)/86400000);if(!d.check_in||!d.check_out||n<=0){toast('تحقق من تواريخ الحجز',false);return;}const localOverlap=bookings.some(x=>x.villa_id===d.villa_id&&x.status!=='cancelled'&&new Date(x.check_in)<b&&new Date(x.check_out)>a);if(localOverlap){toast('يوجد حجز متداخل لهذه الفيلا',false);return;}if(isSupabaseConfigured){const remote=await findOverlap(d.villa_id,d.check_in,d.check_out);if(remote.error||remote.data?.length){toast('رفض الحجز: يوجد تضارب في Supabase',false);return;}}const v=villas.find(x=>x.id===d.villa_id),item={...d,id:`b${Date.now()}`,nights:n,total:n*v.price};try{await persistBooking({...item,total:item.total,nights:item.nights},null);bookings.unshift(item);closeModal();renderRecent();renderBookings();toast('تم إنشاء الحجز بنجاح');}catch(err){toast('تعذر حفظ الحجز',false);}}; }
function invoice(id){const b=bookings.find(x=>x.id===id),jsPDF=window.jspdf?.jsPDF;if(!b||!jsPDF){toast('مكتبة PDF غير متاحة',false);return;}const doc=new jsPDF();doc.setFillColor(15,23,42);doc.rect(0,0,210,297,'F');doc.setTextColor(212,175,55);doc.setFontSize(26);doc.text('VillaTrack',180,30,{align:'right'});doc.setTextColor(230,230,230);doc.setFontSize(18);doc.text('INVOICE',180,48,{align:'right'});doc.setDrawColor(212,175,55);doc.line(25,60,185,60);doc.setFontSize(11);doc.text(`Guest: ${b.guest_name}`,180,80,{align:'right'});doc.text(`Villa: ${villaName(b.villa_id)}`,180,92,{align:'right'});doc.text(`Stay: ${b.check_in}  →  ${b.check_out}`,180,104,{align:'right'});doc.text(`Nights: ${b.nights}`,180,116,{align:'right'});doc.setTextColor(212,175,55);doc.setFontSize(17);doc.text(`Total: ${b.total} LYD`,180,150,{align:'right'});doc.setTextColor(150,160,175);doc.setFontSize(9);doc.text('Thank you for choosing VillaTrack — Luxury stays, beautifully managed.',105,260,{align:'center'});doc.save(`VillaTrack-Invoice-${b.id}.pdf`);toast('تم تنزيل الفاتورة بصيغة PDF');}
function bind(){ document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view)); $('mobileMenu').onclick=()=> $('sidebar').classList.toggle('open'); $('modalClose').onclick=closeModal; $('modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()}; $('quickBookingBtn').onclick=$('addBookingBtn').onclick=bookingForm; $('addVillaBtn').onclick=()=>villaForm(); $('villaSearch').oninput=renderVillas; $('bookingSearch').oninput=renderBookings; $('bookingStatusFilter').onchange=renderBookings; $('villaFilters').onclick=e=>{if(e.target.dataset.filter){villaFilter=e.target.dataset.filter;document.querySelectorAll('#villaFilters button').forEach(x=>x.classList.toggle('active',x===e.target));renderVillas();}}; $('villaGrid').onclick=async e=>{const edit=e.target.dataset.editVilla,del=e.target.dataset.deleteVilla;if(edit)villaForm(villas.find(v=>v.id===edit));if(del&&confirm('حذف هذه الفيلا؟')){try{await removeVilla(del);villas=villas.filter(v=>v.id!==del);renderVillas();calculateStats();toast('تم حذف الفيلا');}catch{toast('تعذر حذف الفيلا',false);}}}; $('bookingsBody').onclick=e=>{if(e.target.dataset.invoice)invoice(e.target.dataset.invoice);}; }
(async function init(){bind();await loadData();calculateStats();renderRecent();renderVillas();renderBookings();drawCharts();})();
